[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Configured for STM32F411CEU6.
runner = "probe-rs run --chip STM32F411CEUx"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"

[alias]
run-firmware = "run --release --bin app"
build-firmware = "objcopy --release --target thumbv7em-none-eabihf --bin app -- -O binary app.bin"
